version: '3'

services:
  backend:
    image: node:14
    container_name: backend
    
    entrypoint: bash
    user: "1000:1000"
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    working_dir: /app
